# Generated by Django 4.0 on 2022-05-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MASH_app', '0002_remove_video_date_uploaded_remove_video_img_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='video',
            table='Link',
        ),
    ]
