# Generated by Django 4.0 on 2022-05-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MASH_app', '0003_alter_video_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='video',
            table='Video',
        ),
    ]
