# Generated by Django 4.0 on 2022-05-10 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MASH_app', '0006_rename_link_video_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First', models.CharField(max_length=256)),
                ('Last', models.CharField(max_length=256)),
                ('Subject', models.CharField(max_length=256)),
                ('Feedback', models.CharField(max_length=256)),
                ('emailf', models.EmailField(max_length=50)),
                ('enrollmentf', models.IntegerField(max_length=12)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MASH_app.master')),
            ],
        ),
    ]
